secrets:
  serverEnv:
    file: ./.env

services:
  moderation-svc:
    restart: unless-stopped
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - "4000:4141"
    secrets:
      - serverEnv
    networks:
      - lyntr_lynternet

networks:
  lyntr_lynternet:
    external: true
